name: Python CI

on: push 
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: install flake8
        run: |
          pip install flake8
      - name: Run linter
        run: |
          make lint
